from enum import StrEnum


class CanonicalCategory(StrEnum):
    ACCESS_CONTROL = "ACCESS_CONTROL"
    AUTH_SIGNATURE = "AUTH_SIGNATURE"
    REENTRANCY = "REENTRANCY"
    ORACLE_PRICE_MANIPULATION = "ORACLE_PRICE_MANIPULATION"
    ACCOUNTING = "ACCOUNTING"
    ARITHMETIC_PRECISION = "ARITHMETIC_PRECISION"
    BUSINESS_LOGIC = "BUSINESS_LOGIC"
    STATE_TRANSITION = "STATE_TRANSITION"
    EXTERNAL_CALL = "EXTERNAL_CALL"
    TOKEN_INTEGRATION = "TOKEN_INTEGRATION"
    FRONTRUNNING_MEV = "FRONTRUNNING_MEV"
    DENIAL_OF_SERVICE = "DENIAL_OF_SERVICE"
    UPGRADEABILITY_INITIALIZATION = "UPGRADEABILITY_INITIALIZATION"
    GOVERNANCE = "GOVERNANCE"
    CROSS_CHAIN_BRIDGE = "CROSS_CHAIN_BRIDGE"
    LIQUIDATION = "LIQUIDATION"
    ECONOMIC_ATTACK = "ECONOMIC_ATTACK"
    RANDOMNESS_TIME = "RANDOMNESS_TIME"
    INPUT_VALIDATION = "INPUT_VALIDATION"
    OTHER = "OTHER"


class Severity(StrEnum):
    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    INFORMATIONAL = "INFORMATIONAL"
    UNKNOWN = "UNKNOWN"


class VerificationStatus(StrEnum):
    UNREVIEWED = "UNREVIEWED"
    VERIFIED = "VERIFIED"
    REJECTED = "REJECTED"


class EvidenceType(StrEnum):
    SOURCE_TEXT = "SOURCE_TEXT"
    CODE_REFERENCE = "CODE_REFERENCE"
    OTHER = "OTHER"


class FindingField(StrEnum):
    TITLE = "title"
    SEVERITY = "severity"
    CANONICAL_CATEGORY = "canonical_category"
    SUMMARY = "summary"
    ROOT_CAUSE = "root_cause"
    IMPACT = "impact"
    RECOMMENDATION = "recommendation"
    AFFECTED_CONTRACT = "affected_contract"
    AFFECTED_FUNCTION = "affected_function"
    SOURCE_FILE = "source_file"
    LINE_START = "line_start"
    LINE_END = "line_end"
    PROTOCOL_NAME = "protocol_name"
    LANGUAGE = "language"
